CREATE SCHEMA transporteparticulartable;

CREATE TABLE transporteparticulartable.CLIENTE_TABLE (
  ID_CLIENTE INTEGER NOT NULL AUTO_INCREMENT,
  NOME_CLIENTE VARCHAR(50) NOT NULL,
  DATA_NASCIMENTO DATE NULL,
  SEXO CHAR(1) NULL,
  CPF VARCHAR(15) NOT NULL,
  NUMERO_CELULAR VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  DATA_CADASTRO DATETIME NULL,
  TIPO_DEFICIENCIA VARCHAR(100) NULL,
  PRIMARY KEY(ID_CLIENTE)
);

CREATE TABLE transporteparticulartable.DETALHES_VEICULOS_TABLE (
  ID_DETALHES_VEICULOS INTEGER NOT NULL AUTO_INCREMENT,
  PLACA_VEICULO VARCHAR(10) NULL,
  COR_VEICULO VARCHAR(25) NULL,
  ACENTOS_VEICULO NUMERIC(2) NULL,
  PRIMARY KEY(ID_DETALHES_VEICULOS)
);

CREATE TABLE transporteparticulartable.VEICULO_TABLE (
  ID_VEICULO INTEGER NOT NULL AUTO_INCREMENT,
  MODELO_VEICULO VARCHAR(25) NULL,
  MARCA_VEICULO VARCHAR(25) NULL,
  DATA_FABRICACAO DATE NULL,
  PRIMARY KEY(ID_VEICULO)
);

CREATE TABLE transporteparticulartable.MOTORISTA_TABLE (
  ID_MOTORISTA INTEGER NOT NULL AUTO_INCREMENT,
  ID_VEICULO INTEGER NULL,
  ID_DETALHES_VEICULOS INTEGER NULL,
  NOME_MOTORISTA VARCHAR(50) NOT NULL,
  DATA_NASCIMENTO DATE NULL,
  SEXO CHAR(1) NULL,
  CPF VARCHAR(15) NOT NULL,
  NUMERO_CELULAR VARCHAR(15) NOT NULL,
  EMAIL VARCHAR(200) NOT NULL,
  SENHA VARCHAR(100) NOT NULL,
  DATA_CADASTRO DATETIME NULL,
  STATUS_MOTORISTA CHAR(1) NOT NULL,
  CARTEIRA_MOTORISTA VARCHAR(12) NOT NULL,
  PRIMARY KEY(ID_MOTORISTA),
  FOREIGN KEY (ID_VEICULO) REFERENCES VEICULO_TABLE(ID_VEICULO),
  FOREIGN KEY (ID_DETALHES_VEICULOS) REFERENCES DETALHES_VEICULOS_TABLE(ID_DETALHES_VEICULOS)
);

CREATE TABLE transporteparticulartable.CARTOES_TABLE (
  ID_CARTOES INTEGER NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INTEGER NOT NULL,
  TIPO_CARTAO VARCHAR(25) NULL,
  BANDEIRA_CARTAO VARCHAR(25) NULL,
  NUMERO_CARTAO NUMERIC(25) NULL,
  PRIMARY KEY(ID_CARTOES),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_TABLE(ID_CLIENTE)
);

CREATE TABLE transporteparticulartable.DINHEIRO_TABLE (
  ID_DINHEIRO INTEGER NOT NULL AUTO_INCREMENT,
  ID_CLIENTE INTEGER NOT NULL,
  TIPO_DINHEIRO VARCHAR(25) NOT NULL,
  PRIMARY KEY(ID_DINHEIRO),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_TABLE(ID_CLIENTE)
);

CREATE TABLE transporteparticulartable.VIAGEM_TABLE (
  ID_VIAGEM INTEGER NOT NULL AUTO_INCREMENT,
  ID_MOTORISTA INTEGER NOT NULL,
  ID_CLIENTE INTEGER NOT NULL,
  ENDERECO_SAIDA VARCHAR(100) NOT NULL,
  ENDERECO_CHEGADA VARCHAR(100) NOT NULL,
  DATA_INICIO DATETIME NOT NULL,
  DATA_FIM DATETIME NOT NULL,
  PRIMARY KEY(ID_VIAGEM),
  FOREIGN KEY (ID_MOTORISTA) REFERENCES MOTORISTA_TABLE(ID_MOTORISTA),
  FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE_TABLE(ID_CLIENTE)
);

CREATE TABLE transporteparticulartable.VIAGEM_ROTA_TABLE (
  ID_VIAGEM_ROTA INTEGER NOT NULL AUTO_INCREMENT,
  ID_VIAGEM INTEGER NOT NULL,
  LATIDUTE DECIMAL(10,8) NOT NULL,
  LONGITUDE DECIMAL(11,8) NOT NULL,
  PRIMARY KEY(ID_VIAGEM_ROTA),
  FOREIGN KEY (ID_VIAGEM) REFERENCES VIAGEM_TABLE(ID_VIAGEM)
);
  
SET GLOBAL time_zone = '-3:00';